### ISSUE TITLE
Mudar usuário do BD para ser readonly

### ISSUE THREAD

**Issue by vitorbaptista** [vitorbaptista/escola-que-queremos#10]
O sistema não escreve nada no BD. Então seria legal se o usuário fosse readonly, assim a gente poderia até colocar o login/senha no repositório, de forma a facilitar outras pessoas contribuírem.

... ou talvez seja uma péssima ideia :P

O que você acha, @tanob?

**Comment by tanob** [comment]
Não entendi o propósito direito, quem for rodar na sua máquina pode ter um login/senha diferente... explica aí :)

**Comment by vitorbaptista** [comment]
Primeiro pensei em usar readonly pra a gente não fazer besteira sem querer.
Depois pensei que, se fosse readonly, poderia deixar no repositório pra
facilitar quem quisesse testar localmente.

Mas acho que é uma ideia besta, desnecessária. Fecha a issue :)
Em 28/04/2013 00:35, "Adriano Bonat" notifications@github.com escreveu:
