### ISSUE TITLE
Retirar dados do SchoolController

### ISSUE THREAD

**Issue by vitorbaptista** [vitorbaptista/escola-que-queremos#11]
Na correria do hackathon, meti um bocado de dados no SchoolController. Agora, com mais calma, era bom retirá-los e colocá-los em um JSON ou algo assim...

**Comment by vitorbaptista** [comment]
Vai que é tua, @camiloribeiro !

**Comment by camiloribeiro** [comment]
Done :) Alguém pode checar o código e me falar o nível de amadorismo que eu fiz?

**Comment by tanob** [comment]
@camiloribeiro por mim tá Ok! Sugiro que envie as contribuições como pull
request e mencione aqui na issue:
1. Fica mais fácil entender o que foi feito ;
2. É mais controlável se tiver algo que possa ser melhorado ou tiver algum
   problema que quebre a app.

@vitorbaptista como gerou esses valores? Temos que colocar esses scripts no
repo.

**Comment by vitorbaptista** [comment]
@tanob Tá naquela gdocs que você e o Pedro estavam usando pra compartilhar queries... seria bom tirar do gdocs e colocar ou no repositório, ou numa página na wiki.

@camiloribeiro Massa! Valeu :+1: Depois concordo com o Adriano que, se estiver com dúvidas em algo e quiser alguém pra fazer review, mete um pull request. Se for coisa besta tá de boa, vai direto pro repositório. E faz as mensagens de commit em português. Também acho estranho, mas começamos assim, era bom manter... :smile:

**Comment by camiloribeiro** [comment]
Valew, Farei isso :+1:
